In [1]:
import numpy as np
import random
import math

hey = ("Hellow World!")
print (hey)

here = ("This is Swarm Intelligence Project: Genetic Algorithm")
print (here) 

Hellow World!
This is Swarm Intelligence Project: Genetic Algorithm


In [2]:
minX1 = -100
maxX1 = 100
minX2 = -100
maxX2 = 100

#panjang chromosome
pchromosome = 20
    

In [3]:
def func1(x1,x2):
    f1 = 0
    f2 = 0
    for i in range(1,6):
        f1 += i*np.cos((i+1)*x1+1)
        f2 += i*np.cos((i+1)*x2+1)
    
    f3 = f1*f2*-1
    return(f3)

In [4]:
#contoh pemanggilan func1(0,2)
func1(0,0)

-65.68348088844648

In [5]:
def func2(x1,x2):
    #fungsi 2
    fu2 = -np.cos(x1)*np.cos(x2)*np.exp(-(x1-np.pi)**2-(x2-np.pi)**2)
    return(fu2)
    
func2(3.14,3.14)

-0.9999923903915094

In [6]:
def fitness(func, x1, x2):
    #pilih nilai c bebas asal diatas 1
    c = 1.2
    
    #variabel nyimpen func
    h = func(x1,x2)
    return(c**h)

In [7]:
fitness(func1, 6, 6)

7.938473308287485e-15

In [8]:
# Decode the population
def decode_chromosome(chromosome):
    
    c1 = int(chromosome/2)
    #c2 = int(chromosome2/2)
    dc1 = np.zeros(chromosome)
    #dc2 = np.zeros(chromosome2)
    dc1[0: c1] = 1
    #dc2[0: c2] = 2
    np.random.shuffle(dc1)
    #np.random.shuffle(dc2)
    return (dc1)
    #return (dc2)
    
 

In [9]:
#testing procedure
print (decode_chromosome(40))

[1. 0. 0. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 1.
 1. 1. 1. 0. 1. 1. 0. 0. 1. 0. 1. 0. 0. 1. 1. 0.]


In [10]:
def create_population(individu, pchromosome):
    
    population = np.zeros((individu, pchromosome))
    for p in range(individu):
        #random.radit buat lucky draw = angka beruntung :D nilai population
        pop = random.randint(0, pchromosome)
        
        population[p, 0:pop] = 1
        
        np.random.shuffle(population[p])
    return (population)

In [11]:
print (create_population(4,10))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 0.]]


In [12]:
#best population
def best_pop(chromosome, population):
    identik = population == chromosome
    
    fitsc = identik.sum(axis=1)
    
    return (fitsc)


In [13]:
#testing
chromosome = decode_chromosome(20)
#output decode chromosome sebanyak 20
print ("Hasil Chromosome: \n", chromosome)

population = create_population(4, 20)
#output population sebanyak 4 kelompok yang terdiri dari 20 biner
print ("\n Hasil Population: \n", population)

best = best_pop(chromosome, population)
print ("\n identik atau terbaik: \n", best)

#fitness_score1 menggunakan function fitness 1 lanjutin yang ini
fitness_score1 = fitness(func1, chromosome, population)
print ("\n fitness terbaik dari function 1: \n",fitness_score1)

#fitness_score2 menggunakan function fitness
fitness_score2 = fitness(func2, chromosome, population)
print ("\n fitness terbaik dari function 2: \n",fitness_score2)

Hasil Chromosome: 
 [0. 0. 1. 1. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0.]

 Hasil Population: 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]

 identik atau terbaik: 
 [10  9 10 11]

 fitness terbaik dari function 1: 
 [[1.10779277e-04 1.10779277e-04 9.80878354e-04 9.80878354e-04
  9.80878354e-04 1.10779277e-04 1.10779277e-04 9.80878354e-04
  9.80878354e-04 1.10779277e-04 1.10779277e-04 9.80878354e-04
  1.10779277e-04 9.80878354e-04 9.80878354e-04 9.80878354e-04
  1.10779277e-04 1.10779277e-04 9.80878354e-04 1.10779277e-04]
 [6.29651350e-06 6.29651350e-06 1.10779277e-04 1.10779277e-04
  1.10779277e-04 6.29651350e-06 6.29651350e-06 1.10779277e-04
  1.10779277e-04 1.10779277e-04 6.29651350e-06 1.10779277e-04
  6.29651350e-06 1.10779277e-04 1.10779277e-04 1.10779277e-04
  6.296

In [14]:
#memilih parent dengan cara turnament breed dengan menggunakan metode atau procedur kromosom dan population
def turney_individu(population, best):
    #dapatkan terlebih dahulu ukuran dari populasinya
    pop_size = len(best) #len mengambil string sebagai parameter
    
    #pilih individu untuk menjadi anggota turnamen
    in1 = random.randint(0, pop_size-1)
    in2 = random.randint(0, pop_size-1)
    
    #score masing masing individu
    sc_ind1 = best[in1]
    sc_ind2 = best[in2]
    
    #bandingkan dan pilih yang terbaik
    if sc_ind1 >= sc_ind2:
        best_ind = in1
    else:
        best_ind = in2
    
    #return individu terbaik untuk dijadikan parent nantinya
    return population[best_ind, :]

In [15]:
# setelah mendapat individu terbaik dari turnamen sebagai bibit dari orangtua

# waktunya untuk test seleksi orang tua

chromosome = decode_chromosome(20)
population = create_population(4,20)
best = best_pop(chromosome, population)

#tampilkan nilai dari kedua orang tua
ortu1 = turney_individu(population, best)
ortu2 = turney_individu(population, best)
print ("Chromosome Orang tua:")
print (ortu1)
print (ortu2)

Chromosome Orang tua:
[0. 1. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1.]
[1. 0. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 1. 0. 1. 0. 1. 1. 0. 0.]


In [16]:
#pemilihan anak/children secara crossover atau Metode Cross Over
def crossover_anak(ortu1,ortu2):
    cr = len(ortu1)
    
    #pilih crossover point menggunakan random randint
    c_point = random.randint(1,pchromosome-1)
    
    anak1 = np.hstack((ortu1[0:c_point],ortu2[0:c_point:]))
    anak2 = np.hstack((ortu2[0:c_point],ortu1[0:c_point:]))
    #menggunakan hstack dari numpy untuk menggabungkan 2 array
    #yaitu array ortu1 dan ortu 2
    
    return (anak1,anak2)

In [17]:
chromosome = decode_chromosome(20)
population = create_population(4,20)
best = best_pop(chromosome, population)

ortu1 = turney_individu(population, best)
ortu2 = turney_individu(population, best)

#panggil prosedur crossover
anak1, anak2 = crossover_anak(ortu1,ortu2)

print ("Chromosome Ortu yang dipakai: \n")
print (ortu1)
print (ortu2)

#hasil anak dari crossover_anak
print ("\n Hasil anak dari crossover: \n")
print (anak1)
print (anak2)

Chromosome Ortu yang dipakai: 

[1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0.]

 Hasil anak dari crossover: 

[1. 0. 1. 1. 1. 0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0. 1. 0. 1. 1. 1.]


In [18]:
def proc_mutasi (population, mutprob): #mutation probability
    
    #random array yang akan dimutasikan'
    random_mut = np.random.random(size=(population.shape))
    
    mut_boolean = random_mut <= mutprob
    
    population[mut_boolean] = np.logical_not(population[mut_boolean])
    
    #return hasil populasi yang sudah di random oleh permutasi
    return(population)

In [19]:
#implementasi mutasi random
chromosome = decode_chromosome(20)
population = create_population(4,20)
best = best_pop(chromosome, population)

ortu1 = turney_individu(population, best)
ortu2 = turney_individu(population, best) 

anak1, anak2 = crossover_anak(ortu1,ortu2)
population = np.stack((anak1,anak2))
print ("Populasi sebelum dimutasi: \n")
print (population)

#masukkan nilai probabilitas untuk dimasukkan ke dalam parameter mutasi
mutprob = 0.1 #nilai probabilitasnya
population = proc_mutasi(population, mutprob)
print ("\n Populasi setelah dimutasi: \n")
print (population)


Populasi sebelum dimutasi: 

[[1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]]

 Populasi setelah dimutasi: 

[[1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 0.]]
